apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-use-psp-nonpriv
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolies']
  verbs: ['use']
  resourceNames:
  - my-psp-nonpriv