apiVersion: certificate.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: tls-svc-csr
spec:
  request: <base64_data_here>
  signerName: kubernetes.io/kubelete-serving
  usages:
  - digital signature
  - key encipherment
  - server auth