apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: pod-using-secret-var
    image: busybox
    command: ['sh', '-c', 'echo "the credential are: $USERNAME:$PASSWORD"']
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-scret
          key: password
          