apiVersion: rbac.authorization.k8s.io/v1
kind: roleBinding
metadata:
  name: rb-use-psp-nonpriv
  namespace: psp-test
roleRef:
  kind: ClusterRole
  name: cr-use-psp-nonpriv
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name:
  namespace: psp-test