apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: busybox
    image: busybox
    env:
    - name: my-user-secret
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: my-password-secret
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
